batch_size: 64
train_batch_size: 64
val_batch_size: 64
data_root:  None
num_train_images: -1 # Dataloader convert -1 into None obj.
num_val_images: -1
num_workers: 4
in_channels: 1
seed: 1
name: musan