FileLoader:
  min_duration: 1
  normalize: true
  remove_silence: false
  sample_rate: 16000
  type: TIMIT
FileSampler:
  dataset_dirs:
  - /home/lev/datasets/TIMIT/data/TRAIN
  - /home/lev/datasets/TIMIT/data/TRAIN
  - /home/lev/datasets/TIMIT/data/TRAIN
  - /home/lev/datasets/TIMIT/data/TRAIN
  - /home/lev/datasets/TIMIT/data/TRAIN
  dataset_names:
  - speech1
  - speech2
  - speech3
  - speech4
  - speech5
  dataset_prob:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  dataset_split: test
  min_datasets: 5
  replace: false
  seed: 42
  test_size: 0.25
SequentialFileProcessor:
  num_files_generate: 100
  save_config_dir: /home/lev/audio2/RadioDataset/save_dir
  save_dir: /home/lev/audio2/RadioDataset/save_dir
transform_chain:
  ExtractAndFade: {}
  MelSpectrogram:
    db: true
    hop_length: 220
    n_fft: 1024
    n_mels: 128
    sample_rate: 16000
    top_db: 120
    win_length: 1024
    x_output_size: 128
  MinMaxScaler: {}
  SequentialConcatenator: {}
  TIMITSegmentSilenceSampler:
    final_audio_clip_duration: 1.78
    max_total_silence_dur: 0.3
    min_segment_silence_dur: 0
    sampling_rate: 16000
  TransitionSegmentSilenceParametersSampler:
    in_transition_type:
    - linear
    - logarithmic
    - exponential
    - half_sine
    max_fade_in: 0.1
    max_fade_out: 0.1
    min_fade_in: 0.05
    min_fade_out: 0.05
    out_transition_type:
    - linear
    - logarithmic
    - exponential
    - half_sine
