resolution: [128,128]
num_slots:  5
num_iterations: 3
empty_cache: True
n_samples: 5
loss_type: KL
kl_loss_reg: 0.05
#slot attention parameters
slot_size: 64
mlp_hidden_size: 128
kernel_size: 5
decoder_resolution: [8,8]
hidden_dims: [64, 64, 64, 64]

opt: 
  lr: 0.0004
  warmup_steps_pct: 0.2
  decay_steps_pct: 0.15
  weight_decay: 0.0
  max_epochs: 1
  scheduler_gamma: 0.5







