resolution: [128,128]
num_slots:  5
num_iterations: 3
empty_cache: True
n_samples: 5
hidden_dims: [64, 64, 64, 64]
kernel_size: 5
opt: 
  lr: 0.0004
  warmup_steps_pct: 0.02
  decay_steps_pct: 0.1
  weight_decay: 0.0
  max_epochs: 500
  scheduler_gamma: 0.5





