save_dir: #['/home/lev/datasets/musan/speech', '/home/lev/datasets/musan/music']

dataset_dirs: ['/home/lev/datasets/musan/speech', '/home/lev/datasets/musan/music','/home/lev/datasets/musan/music']
sampler:
  dataset_dirs: ['/home/lev/datasets/musan/speech', '/home/lev/datasets/musan/music', '/home/lev/datasets/musan/music']
  dataset_names: [speech, musan, musan2]
  dataset_prob: [0.4, 0.4, 0.2]
  replace: True
  seed: 10
loader: 
  sample_rate: 22050
  remove_silence: True
  normalize: True
  min_duration: 1
TransitionGenerator:
  min_segment_length: 1
  sample_rate: 22050
  final_audio_clip_length: 2.2
  min_duration_between_trans: 0.1

  max_fade_out: 0.5 # percentage/100
  min_fade_out: 0.2 # percentage/100
  max_fade_in: 0.5  # percentage/100
  min_fade_in: 0.2 # percentage/100

  max_time_gap: 0.2
  max_music_gain: 0.7
  max_n_transition: 2 # 2 means in fact 1
  in_transition_type: ['linear', 'logarithmic', 'exponential', 'half_sine']
  out_transition_type: ['linear', 'logarithmic', 'exponential', 'half_sine']
Audio_sampler:
  sr: 22050
  audio_total_dur: 2.2
  segment_min: 0.5

Silence_sampler:
  sr: 22050
  max_total_silence_dur: 0.2
  minimum_segment_silence_dur: 0.1


file_preprocessor: None
