#save_dir: '/home/lev/audio2/RadioDataset/save_dir'
SequentialFileProcessor:
  num_files_generate: 10
  save_dir: "/home/lev/audio2/RadioDataset/save_dir" #'/home/lev/audio2/RadioDataset/Datasets/dataset1/files'
  save_config_dir: "/home/lev/audio2/RadioDataset/save_dir" #'/home/lev/audio2/RadioDataset/Datasets/dataset1'

FileSampler:
  dataset_dirs: ['/home/lev/datasets/musan/speech', '/home/lev/datasets/musan/music', '/home/lev/datasets/musan/music']
  dataset_names: [speech, musan, musan2]
  dataset_prob: [0.4, 0.4, 0.2]
  replace: True
  seed: 10

FileLoader: 
  # dataset_unique_label: 
  #   speech: 0
  #   musan: 1
  #   musan2: 2
  sample_rate: 22050
  remove_silence: True
  normalize: True
  min_duration: 1

transform_chain:
  SegmentSilenceSampler:
    # Segment sampler parameters
    sampling_rate: 22050
    final_audio_clip_duration: 2.2
    segment_min_duration: 0.5

    # silence sampler parameters
    max_total_silence_dur: 0.2
    min_segment_silence_dur: 0.1

  TransitionSegmentSilenceParametersSampler:
    # Fade in 
    max_fade_in: 0.5  # percentage/100
    min_fade_in: 0.2 # percentage/100
    in_transition_type: ['linear', 'logarithmic', 'exponential', 'half_sine']

    # Fade out 
    max_fade_out: 0.5 # percentage/100
    min_fade_out: 0.2 # percentage/100
    out_transition_type: ['linear', 'logarithmic', 'exponential', 'half_sine']

  ExtractAndFade: {}
  SequentialConcatenator: {}
  MelSpectrogram:
    n_fft: 1024
    win_length: 1024
    hop_length: 220
    n_mels: 128
    sample_rate: 22050
    # Power to DB
    db: True
    top_db: 120

    # Cut time dimention if needed
    x_output_size: #None

  MinMaxScaler: {}




    
    
    
    
    

    








  











