#save_dir: '/home/lev/audio2/RadioDataset/save_dir'

SequentialFileProcessor:
  num_files_generate: 2000
  save_dir: '/home/lev/audio2/RadioDataset/Datasets/TIMITphonems/test'
  save_config_dir: '/home/lev/audio2/RadioDataset/Datasets/TIMITphonems'

FileSampler:
  dataset_split: test
  test_size: 0.25
  seed: 0

  dataset_dirs: ['/home/lev/datasets/TIMIT/data/TRAIN', '/home/lev/datasets/TIMIT/data/TRAIN', '/home/lev/datasets/TIMIT/data/TRAIN', '/home/lev/datasets/TIMIT/data/TRAIN', '/home/lev/datasets/TIMIT/data/TRAIN']
  dataset_names: [speech1, speech2, speech3, speech4, speech5]
  min_datasets: 5
  dataset_prob: [0.2, 0.2, 0.2, 0.2, 0.2]
  replace: False
  seed: 42

FileLoader: 
  sample_rate: 16000
  remove_silence: True
  normalize: True
  # minimum duration of loaded file
  min_duration: 1
FileSaver:


transform_chain:
  SegmentSilenceSampler:
    # Segment sampler parameters
    sampling_rate: 16000
    final_audio_clip_duration: 1.78
    segment_min_duration: 0.08
    segment_max_duration: 0.18

    # silence sampler parameters
    max_total_silence_dur: 0.3
    min_segment_silence_dur: 0

  TransitionSegmentSilenceParametersSampler:
    # Fade in 
    max_fade_in: 0.1  # percentage/100
    min_fade_in: 0.05 # percentage/100
    in_transition_type: ['linear', 'logarithmic', 'exponential', 'half_sine']

    # Fade out 
    max_fade_out: 0.1 # percentage/100
    min_fade_out: 0.05 # percentage/100
    out_transition_type: ['linear', 'logarithmic', 'exponential', 'half_sine']

  ExtractAndFade: {}
  SequentialConcatenator: {}
  MelSpectrogram:
    n_fft: 1024
    win_length: 1024
    hop_length: 220
    n_mels: 128
    sample_rate: 16000
    # Power to DB
    db: True
    top_db: 120

    # Cut time dimention if needed
    x_output_size: 128

  MinMaxScaler: {}




    
    
    
    
    

    








  











